# Generated by Django 4.2.2 on 2023-06-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='firstname',
            new_name='name',
        ),
    ]
